# Frontend CI/CD Pipeline

name: Frontend Pipeline

# Trigger on push to 'main' branch, only for changes in 'frontend/'
on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  # Test: Run Cypress tests
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start local server
        working-directory: frontend/public
        run: |
          python3 -m http.server 5000 &
          sleep 5

      - name: Install Cypress
        run: npm install cypress --save-dev

      - name: Run tests
        working-directory: frontend/tests
        run: npx cypress run

  # Deploy: Sync frontend code with S3
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync frontend code with S3 bucket
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: crc-fbrpinto-s3-tf
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-1'
          SOURCE_DIR: 'frontend/public'
