name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install cypress --save-dev
        
      - name: Change directory to tests
        run: cd tests/frontend

      - name: Run Cypress tests
        run: npx cypress run --spec "cypress/e2e/spec.cy.js" 
