name: Cypress Tests

on:
  push:
    branches:
    - main
    paths:
    - 'frontend/public/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
    - uses: actions/checkout@v4

    - name: Sync frontend code with s3 bucket
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: crc-fbrpinto-s3-tf
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-1'
        SOURCE_DIR: 'frontend/public'
  
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install cypress --save-dev
        
      - name: Change directory and run Cypress tests
        run: cd tests/frontend && npx cypress run
