name: Frontend Pipeline

on:
  push:
    branches:
    - main
    paths:
    - 'frontend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Start local server
      working-directory: frontend/public
      run: npx serve -s . -l 5000

    - name: Wait for server
      run: sleep 5

    - name: Run tests
      working-directory: frontend/tests
      run: npx cypress run --config-file cypress.config.component.js
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Sync frontend code with s3 bucket
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: crc-fbrpinto-s3-tf
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-1'
        SOURCE_DIR: 'frontend/public'