# Infrastructure CI/CD Pipeline

name: Infrastructure Pipeline

# Trigger on push to 'main' branch, only for changes in 'infrastructure/' (or manually)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'

# Allow requesting an OIDC token to sign in to AWS
permissions:
  id-token: write
  contents: read

# Cloudflare API token for the DNS records
env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

jobs:
  # Deploy: Frontend infrastructure using Terraform
  deploy_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure/frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: "eu-west-1"

      - name: Generate TFVars file
        run: |
          echo "domain_name = \"${{ vars.DOMAIN_NAME }}\"" > terraform.auto.tfvars
          echo "cloudflare_zone_id = \"${{ secrets.CLOUDFLARE_ZONE_ID }}\"" >> terraform.auto.tfvars

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

  # Deploy: Backend infrastructure using Terraform
  deploy_backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure/backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: "eu-west-1"

      - name: Generate TFVars file
        run: |
          echo "slack_webhook = \"${{ secrets.WEBHOOK_SLACK }}\"" > terraform.auto.tfvars
          # Disabled: PagerDuty no longer used
          # echo "pagerduty_webhook = \"${{ secrets.WEBHOOK_PAGERDUTY }}\"" >> terraform.auto.tfvars
          echo "notification_email = \"${{ secrets.NOTIFICATION_EMAIL }}\"" >> terraform.auto.tfvars
          echo "api_domain = \"${{ vars.API_DOMAIN }}\"" >> terraform.auto.tfvars
          echo "cloudflare_zone_id = \"${{ secrets.CLOUDFLARE_ZONE_ID }}\"" >> terraform.auto.tfvars

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
