name: Deploy infrastructure using Terraform

on:
  push:
    branches:
    - main
    paths:
    - 'infrastructure/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
jobs:
  deploy_frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infrastructure/frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Generate TFVars file
        working-directory: infrastructure/frontend
        run: |
          echo "domain_name = \"${{ vars.DOMAIN_NAME }}\"" > terraform.auto.tfvars
          echo "hosted_zone_id = \"${{ secrets.HOSTED_ZONE_ID }}\"" >> terraform.auto.tfvars
        
      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy
      
      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
