name: Terraform Workflow

on:
  push:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Generate TFVars file
        working-directory: infrastructure
        run: |
          echo "aws_region = \"$AWS_REGION\"" > terraform.auto.tfvars
          echo "bucket_name = \"$BUCKET_NAME\"" >> terraform.auto.tfvars
          echo "certificate_arn = \"$CERTIFICATE_ARN\"" >> terraform.auto.tfvars
          echo "hosted_zone_id = \"$HOSTED_ZONE_ID\"" >> terraform.auto.tfvars
        env:
          CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
        

      - name: Terraform Init
        working-directory: infrastructure
        run: terraform init
      
      - name: Terraform Plan
        working-directory: infrastructure
        run: terraform plan

      - name: Terraform Apply
        working-directory: infrastructure
        run: terraform apply -auto-approve
