name: Terraform Workflow

on:
  push:
    branches:
    - main
    paths:
    - 'infrastructure/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Generate TFVars file
        working-directory: infrastructure
        run: |
          echo "aws_region = \"${{ vars.AWS_REGION }}\"" > terraform.auto.tfvars
          echo "bucket_name = \"${{ vars.BUCKET_NAME }}\"" >> terraform.auto.tfvars
          echo "certificate_arn = \"${{ secrets.CERTIFICATE_ARN }}\"" >> terraform.auto.tfvars
          echo "hosted_zone_id = \"${{ secrets.HOSTED_ZONE_ID }}\"" >> terraform.auto.tfvars
        

      - name: Terraform Init
        working-directory: infrastructure
        run: terraform init
      
      - name: Terraform Plan
        working-directory: infrastructure
        run: terraform plan

      - name: Terraform Apply
        working-directory: infrastructure
        run: terraform apply -auto-approve
